const numbers = [
  { num: 0, word: "Zero" },
  { num: 1, word: "One" },
  { num: 2, word: "Two" },
  { num: 3, word: "Three" },
  { num: 4, word: "Four" },
  { num: 5, word: "Five" },
  { num: 6, word: "Six" },
  { num: 7, word: "Seven" },
  { num: 8, word: "Eight" },
  { num: 9, word: "Nine" },
  { num: 10, word: "Ten" },
  { num: 11, word: "Eleven" },
  { num: 12, word: "Twelfth" },
  { num: 13, word: "Thirteen" },
  { num: 14, word: "Fourteen" },
  { num: 15, word: "Fifteen" },
  { num: 16, word: "Sixteen" },
  { num: 17, word: "Seventeen" },
  { num: 18, word: "Eighteen" },
  { num: 19, word: "Nineteen" },
  { num: 20, word: "Twenty" },
  { num: 30, word: "Thirty" },
  { num: 40, word: "Forty" },
  { num: 50, word: "Fifty" },
  { num: 60, word: "Sixty" },
  { num: 70, word: "Seventy" },
  { num: 80, word: "Eighty" },
  { num: 90, word: "Ninety" },
];

const counters = [
  "",
  "thousand",
  "million",
  "billion",
  "trillion",
  "quadrillion",
  "quintillion",
  "sextillion",
  "septillion",
  "octillion",
  "nonillion",
  "decillion",
  "undecillion",
  "duodecillion",
  "tredecillion",
  "quattuordecillion",
  "quindecillion",
  "sexdecillion",
  "septendecillion",
  "octodecillion",
  "novemdecillion",
  "vigintillion",
];

module.exports = { numbers, counters };
